### ISSUE TITLE
Missing 'package:dart_hub/keys.dart';

### ISSUE THREAD

**Issue by kostaa** [SamThompson/dart_hub#7]
Looks like you have not checked in 'package:dart_hub/keys.dart'. It is imported in the auth_manager.dart.

**Comment by SamThompson** [comment]
Yes, that's intentional because keys.dart contains my app's client id and client secret. If you'd like to build and run this project, you'll need to create one and define two constants (CLIENT_ID and CLIENT_SECRET) inside it.
